### ISSUE TITLE
Add JsonSerializerSettings in Global configuration for Request Body

### ISSUE THREAD

**Issue by all4peace** [apimatic/core-lib-csharp#38]
I encountered an error because the serialization of objects didn't change it to camel case, which the end point was expecting. As such, I recommend adding to the configuration the ability to specify deserialization settings.

Here is what I propose:

```
_globalConfiguration = new GlobalConfiguration.Builder()
    .AuthManagers(new Dictionary<string, AuthManager> {
        { "global", new BearerAuthManager(accessToken) }
    })
    .HttpConfiguration(new CoreHttpClientConfiguration.Builder().Build())
    .ServerUrls(urlMap, Server.Default)
    .JsonSerializerSettings(new JsonSerializerSettings
    {
        ContractResolver = new DefaultContractResolver
        {
            NamingStrategy = new CamelCaseNamingStrategy()
        },
        MaxDepth = 128
    })
    .UserAgent(USER_AGENT)
    .Build();

```

I applied this logic for my current project and it worked smoothly. But I think solution should also consider XML serialization which my work didn't consider/take into account.

Hope this helps, and if you want the current solution, I'm happy to push a PR.

**Comment by all4peace** [comment]
I forgot to mention, debugging was a bit a pain because the ExecuteAsync doesn't return the context. I made a change to add that as an option.

**Comment by hamzamahmood** [comment]
Hi @all4peace

Sorry for getting back to you late on this. The property names can be modified using the `JsonPropertyAttribute` specified over the properties in the model classes to match the endpoint requirements. The `apimatic/core-lib-csharp` specifically is designed to be used with the auto-generated C# SDKs by APIMatic. The models auto-generated in the C# SDK use the serialization attributes from the API specification file. We also support a basic level of XML serialization. More information on the SDK generation using APIMatic can be found here https://www.apimatic.io/.

Furthermore, you can get the context using the `ContextAdder` delegate in `ApiCall > ResponseHandler`

I hope this helps!
